---
title: "HW 03 - Great Lakes Fish Datasets"
author: "Insert your name here"
date: "Insert date here"
output: html_document
---

## Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse)
```

```{r load-data, message = FALSE}
catch_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/fishing.csv')

fish_stock <- read_csv("data/great-lakes-fish-stock.csv")
```

## Exercises

### Exercise 1

```{r catch-data-subset}
catch_data <- catch_data %>% 
  select(year, lake, species, grand_total)
```

```{r fish-stock-subset}
fish_stock <- fish_stock %>% 
  select(-NO_STOCKED, -AGEMONTH)
```

### Exercise 2

Remove this text, and add your answer for Exercise 2 here.

### Exercise 3

Remove this text, and add your answer for Exercise 3 here.

```{r label-me-1}
# remove this comment and add the code for Exercise 3 here
```

### Exercise 4

Remove this text, and add your answer for Exercise 4 here.

```{r label-me-2}
# remove this comment and add the code for Exercise 4 here
```
