---
title: "Homework 06 - Iterating functions on Chicago cold"
author: "RUBRIC"
date: "RUBRIC"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse)
library(lubridate)
```

## Exercises

### Exercise 1

```{r import-convert-temperatures, eval = T}
source("convert_temperature.R")
```

### Exercise 2

```{r test-function}
convert_temperature(32)
```

### Exercise 3

```{r import-data}
loop <- read_csv("data/chicago-loop.csv")
south_loop <- read_csv("data/chicago-south-loop.csv")
oak_park <- read_csv("data/chicago-oak-park.csv")
```

```{r glimpse-data}
glimpse(loop)
glimpse(south_loop)
glimpse(oak_park)
```

### Exercise 4

```{r import-data-fix-dates}
loop <- read_csv("data/chicago-loop.csv", col_types = list(col_date(), 
                                                        col_double(), 
                                                        col_double(),
                                                        col_double())
                 )
south_loop <- read_csv("data/chicago-south-loop.csv", col_types = list(col_date(), 
                                                        col_double(), 
                                                        col_double(),
                                                        col_double())
                      )
oak_park <- read_csv("data/chicago-oak-park.csv", col_types = list(col_date(), 
                                                        col_double(), 
                                                        col_double(),
                                                        col_double())
                    )
```

```{r glimipse-data-2}
glimpse(loop)
glimpse(south_loop)
glimpse(oak_park)
```

### Exercise 5

```{r wrangle-and-merge-data}
loop <- loop %>% 
  mutate(neighborhood = "loop") %>% 
  relocate(neighborhood)

south_loop <- south_loop %>% 
  mutate(neighborhood = "south_loop") %>% 
  relocate(neighborhood)

oak_park <- oak_park %>% 
  mutate(neighborhood = "oak_park") %>% 
  relocate(neighborhood)

chicago_temperatures <- loop %>% 
  bind_rows(south_loop) %>% 
  bind_rows(oak_park)
```

### Exercise 6

```{r plot-neighborhood-temperatures}
chicago_temperatures %>% 
  ggplot(aes(x = date, y = temperature_high, color = neighborhood)) +
  geom_line() +
  theme_bw()
```

### Exercise 7

It appears that most of the time, the loop was the coldest neighborhood, which does not support the hypothesis that the lake would keep lakeshore neighborhoods warmer.

### Exercise 8

```{r create-list}
chicago_temperatures_list <- list(chicago_temperatures$temperature_high,
                                  chicago_temperatures$temperature_avg,
                                  chicago_temperatures$temperature_low)
```

### Exercise 9

```{r apply-convert-temperature}
chicago_temperatures_converted <- map_df(chicago_temperatures_list, convert_temperature)
```

### Exercise 10

```{r rejoin-data, eval = T}
chicago_temperatures %>% 
    pivot_longer(
    names_to = "measurement",
    values_to = "fahrenheit",
    cols = 3:5
  ) %>% 
  select(neighborhood, date) %>% 
  bind_cols(chicago_temperatures_converted)
```
